steps:
  - id: build
    name: gcr.io/cloud-builders/docker
    args:
      - build
      - --tag
      - ${_LOCATION}-docker.pkg.dev/${PROJECT_ID}/containers/moneysaver:$COMMIT_SHA
      - --tag
      - ${_LOCATION}-docker.pkg.dev/${PROJECT_ID}/containers/moneysaver:latest
      - .
  - id: push
    name: gcr.io/cloud-builders/docker
    entrypoint: '/bin/bash'
    args:
      - -c
      - |-
        docker push ${_LOCATION}-docker.pkg.dev/${PROJECT_ID}/containers/moneysaver:$COMMIT_SHA
        docker push ${_LOCATION}-docker.pkg.dev/${PROJECT_ID}/containers/moneysaver:latest
    waitFor: ['build']

